name: panzetapp
description: Flutter app that lets you manage your Panzeta's weekly menu subscriptions, and see the upcoming monthly events on Createthrive
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animations: ^2.0.7  
  bloc: ^8.1.1
  delayed_display: ^2.0.0
  drawing_animation: ^1.0.1
  cached_network_image: ^3.2.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  liquid_swipe: ^3.1.0
  rect_getter: ^1.1.0
  smooth_page_indicator: ^1.0.1
  step_progress_indicator: ^1.0.2
  transparent_image: ^2.0.1

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Black.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Black.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-ExtraLight.ttf
        - asset: assets/fonts/LexendDeca-Medium.ttf
        - asset: assets/fonts/LexendDeca-SemiBold.ttf
